### ISSUE TITLE
Reset zoom to 1 after hiding video-review

### ISSUE THREAD

**Issue by eonist** [eonist/HybridCamera#21]
Ref to proposed solution: https://github.com/eonist/HybridCamera/pull/19#issuecomment-514407025

**Comment by blurtime** [comment]
The proposed solution works fine although the user will always see how the zoom is suddenly reset after exiting. Therefore, I decided to do the resetting in the `let processMediaView: CustomProcessView = {` closure instead which gets rid of this minor aesthetic issue right away. 
I'm not sure if it is required but I'm resetting it in the `initiate()`, too. Therefore, I decided to create a function. Feel free to change this, though, if you think it is unnecessary.
I'll create a PR and reference it in a few minutes.

Slowly but surely getting the hang of callbacks and starting to love them btw 😌

**Comment by eonist** [comment]
Right. I also changed how we create the review-view now, to fix mem-leak . See latest commit in dev.

**Comment by blurtime** [comment]
The latest commit is still from me (12 hours ago). Do you mean the commits from you before that?

**Comment by eonist** [comment]
Sorry forgot to push. Online now.

**Comment by blurtime** [comment]
I still can't see any new commits... Sure, you pushed it already?

**Comment by blurtime** [comment]
#23
