### ISSUE TITLE
Volume too low in CustomProcessView

### ISSUE THREAD

**Issue by blurtime** [eonist/HybridCamera#22]
I'm gonna go ahead and follow your advice of creating issues first and then PRs, so here a small suggestion. I already have the code written out and it works as it's supposed to. But I'm pretty tired now so I am gonna go to bed now and create the PR tomorrow. The issue:

The videos' volumes seem very low when playing them in the `CustomProcessView`. The volume is higher, though, when you play them in the Photos app after saving them. Accordingly, I wrote some code to switch back and forth between the `AVAudioSession.Category`s `.playAndRecord` & `.playback` (the latter for `CustomProcessView`) such that the volume is normal when playing the video after recording it.

**Comment by eonist** [comment]
Cool. Also make sure Spotify or bg-music still works.

**Comment by blurtime** [comment]
I don't know why but even when I use the current master my music stops playing and I'm unable to record anything without bugs when I continue playing it again. Does this occur on your side, too?
I can add my code to the `develop` branch but this would mean that Spotify would be definitely interrupted when watching your recorded video in the process view and one would have to add further code to so to say hit play again when going back to the camera. Would you like me to still add the code?

**Comment by eonist** [comment]
Right. Forget about Spotify for now. Apple changed something since last year. It will have to be fixed in another PR. Once that is relevant for someone.

**Comment by blurtime** [comment]
Ok, then I'll go ahead and add my code, right?

**Comment by eonist** [comment]
Yepp. Just branch from dev. And create a PR:

**Comment by eonist** [comment]
Now. Sorry vacation mode. :D

**Comment by blurtime** [comment]
Alright :D I'm gonna close the remaining issues after creating the pull requests and probably gonna do the rest I need for my project on my own, as it is probably out of scope for this library. Then you can test them whenever you have time and let me know when you merge them with the master :) 
If at any point there are some small PRs or features and you don't have enough time, let me know and I'll take a look at them and see if can take some work off of you. Loved working with you so far and thank you for introducing me to call-backs! 
Enjoy your vacation! 😁

**Comment by eonist** [comment]
No worries. I'm probably going to Add auto layout and animation to this lib tomorrow and make a nice gif to showcase how it works. And maybe launch on product hunt. 😅 Stay tuned.

**Comment by blurtime** [comment]
#23
