### ISSUE TITLE
iOS13

### ISSUE THREAD

**Issue by Dfmarulanda** [eonist/HybridCamera#28]
no background task exists with identifier 20 (0x14), or it may have already been ended at iOS 13

**Comment by eonist** [comment]
Do you want me to update for iOS 13?
- Could you provide more context? I would love to help.

**Comment by Dfmarulanda** [comment]
I love this library; im developing a instagram like functionality using this lib + lottie. Sometimes it doesn't work but is not because iOS13, i think the camera get's locked when you close the app without dismissing the controller.

**Comment by eonist** [comment]
Ill take a look after work tomorrow 👍

**Comment by eonist** [comment]
Made some improvements. Will continue tomorrow ✌️

**Comment by eonist** [comment]
@Dfmarulanda  Adding iOS 13 tonight
