### ISSUE TITLE
Microphone is not working when recording video.

### ISSUE THREAD

**Issue by Mitesh-Mewada** [eonist/HybridCamera#4]
great tutorial,
  When i start a shooting a video than time microphone is not working how to resolve this problem.

**Comment by eonist** [comment]
@Mitesh-Mewada Could be the same problem this guy had: https://github.com/eonist/HybridCamera/issues/2#issuecomment-422370438

**Comment by eonist** [comment]
Resolved in https://github.com/eonist/HybridCamera/commit/73ec5b9fdda282b091acc754e7bc34dbd3c2bda4
