### ISSUE TITLE
How to use 'WideAngleCamera' in HybridCamera project 

### ISSUE THREAD

**Issue by shamdass** [eonist/HybridCamera#45]
Hello Eonist,

I am trying to use WideAngleCamera in HybridCamera. please suggest me how to use WideAngleCamera in project.

Thank you

**Comment by eonist** [comment]
Im adding support for this AS we speak. If tou look at the latest commits it supports telelense. You can Add ultramoderne angle in the same manor. Im adding tripple lense support this weekend if tou dont want to Add it your self. Ill link the repo where the new switcher is located when i Get home from work today.

**Comment by shamdass** [comment]
Okay @eonist Please reply  ASAP.

**Comment by eonist** [comment]
@shamdass ✅ https://github.com/eonist/HybridCamera/pull/46
