### ISSUE TITLE
Preview view vs. Actual photo do not show the exact same thing

### ISSUE THREAD

**Issue by mathieut** [eonist/HybridCamera#55]
It seems like the preview view and the actual photos taken don't match. The photo shows a slightly more wide view.

**Comment by eonist** [comment]
This camera crops the shot to fit the entire screen. You could keep the ratio, but then you would have big black bars top and bottom. I think the apple camera app now uses 2 cameras to fake this effect. they put the perspective camera in the bars so to speak. Im not sure they do. Just a theory.
