### ISSUE TITLE
ResultSugar "pin" in `Package.resolved` points to a non-existing commit hash

### ISSUE THREAD

**Issue by agurtovoy** [eonist/HybridCamera#56]
According to GitHub, the https://github.com/eonist/ResultSugar.git repo no longer includes this commit:

https://github.com/eonist/HybridCamera/blob/69014ad7adaa345d0617f6d576e08ffe818562ab/Package.resolved#L9

```
$ swift build
Fetching https://github.com/eonist/ResultSugar.git from cache
Fetched https://github.com/eonist/ResultSugar.git (0.62s)
https://github.com/eonist/ResultSugar.git @ 62da1bb61e937dd491cc9cea40f8785a2dc92a08: error: could not find the commit 62da1bb61e937dd491cc9cea40f8785a2dc92a08 in https://github.com/eonist/ResultSugar.git
```

Deleting `Package.resolved` resolves this (pun intended :).

**Comment by agurtovoy** [comment]
I spoke too soon; deleting `Package.resolved` in the repo's root only fixes the issue if you're building from CLI using `swift build` command, but it turns out XCode also embeds a copy of `Package.resolved` under https://github.com/eonist/HybridCamera/blob/master/HybridCamera.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, which also needs to be updated — either manually, or by invoking _File > Packages > Update to Latest Package Versions_ menu command.

**Comment by eonist** [comment]
I deleted the .resolved file. It doesn't need to be in the repo. Should be excluded TBH

**Comment by agurtovoy** [comment]
@eonist Yep, I'd suggest deleting and `.gitignore`-ing the one inside of the xcodeproj folder as well.
