### ISSUE TITLE
Maximum record duration = 20 seconds, is not working

### ISSUE THREAD

**Issue by SathiyakumarIOS** [eonist/HybridCamera#7]
When we set the maximum record duration to 20 sec, is not working. But its working fine when we set 10 sec.

**Comment by eonist** [comment]
This library has no record duration property. Use https://github.com/eonist/SimpleTimer/ and add it to the RecordButton if you need that.

**Comment by SathiyakumarIOS** [comment]
Hi eonist, I'm new to swift, Could u pls add this timer class to RecordButton and update the solution files in project please.

**Comment by eonist** [comment]
`When we set the maximum record duration to 20 sec` where did you set this?

**Comment by eonist** [comment]
@[SathiyakumarIOS](/SathiyakumarIOS)

You can use: 
https://github.com/eonist/SimpleTimer

Something like: 

```swift
let timer =  SimpleTimer(interval: 1, repeats: true)
var totalTime:Int = 0
timer.tick = {
   if totalTime == 10 {
      camera.stop()
   }
   totalTime += 1
}
onLongClick(){
   timer.start()
}
onLongRelease(){
   timer.stop()
}

```

If you are going to work with AVFoundation implementing a timer method on the record button is about as easy as it gets. 

The AVFoundation framework is a beast of complexity and things will get complicated.

Best of luck and let me know if you have any other questions

**Comment by SathiyakumarIOS** [comment]
In CamView.swift,
There we have a variable called "videoOutput", its declared like,
public let videoOutput = AVCaptureMovieFileOutput().

Within the "init" method,
I have set "videoOutput.maxRecordedDuration = CMTimeMake(value: 20, timescale: 1)"

By using the above code, it will automatically stops recording when the duration reaches 20 sec. The recorded video playing without voice. Please help me to resolve.

**Comment by eonist** [comment]
I think its better to do this within the start / stop functionality of the RecordButton. As you need give the user feedback that the video stopped anyway. 

The microphone support for video was fixed before: https://github.com/eonist/HybridCamera/issues/4

Last time I tested it, it worked.

**Comment by SathiyakumarIOS** [comment]
When i force stop recording manually like "hybridCamView.camView.stopRecording()". The voice gets muted

**Comment by eonist** [comment]
That suppose to happen no? If you record a video with instagram and you stop recording then audio recording stops as well.

**Comment by SathiyakumarIOS** [comment]
Hi enoist, please look at my coding, I have stopped recording as like in the picture, please have a look.
![screenshot_1](https://user-images.githubusercontent.com/47453128/52999538-14a49500-344c-11e9-96e9-fa6f2bc675a0.png)
![screenshot_2](https://user-images.githubusercontent.com/47453128/52999540-166e5880-344c-11e9-8a8b-4bcba789e97e.png)

If am wrong, please help me to resolve.

**Comment by eonist** [comment]
I don’t understand what you want to achieve. The lib works like this; you press and hold the record button to record, when you lift your finger it stops. It works for 3,5,10,20,60 seconds. How ever long you hold it down.

**Comment by SathiyakumarIOS** [comment]
"Am looking to stop recording without lifting my finger" this is what am trying to achieve. Hope now your clear about my question.

**Comment by eonist** [comment]
Right. Just call stop after 10 seconds. Thats it. And disable calling stop twice when the user eventually lift his finger. It may take some elbow grease to get just perfect. Good luck. Shouldn’t be too hard.
